const PREFIX = "@@grocery/";

export const FETCH_LIST_REQUEST = `${PREFIX}FETCH_LIST_REQUEST`;
export const FETCH_LIST_FAILURE = `${PREFIX}FETCH_LIST_FAILURE`;
export const FETCH_LIST_SUCCESS = `${PREFIX}FETCH_LIST_SUCCESS`;

export const ADD_GROCERY_LIST_ITEM = `${PREFIX}ADD_GROCERY_LIST_ITEM`;

export const SAVE_LIST_ITEM_REQUEST = `${PREFIX}SAVE_LIST_ITEM_REQUEST`;
export const SAVE_LIST_ITEM_FAILURE = `${PREFIX}SAVE_LIST_ITEM_FAILURE`;
export const SAVE_LIST_ITEM_SUCCESS = `${PREFIX}SAVE_LIST_ITEM_SUCCESS`;